### ISSUE TITLE
ML jobs seem to prevent monitoring from being enabled

### ISSUE THREAD

**Issue by cachedout** [elastic/stack-monitoring#46]
Elasticsearch monitoring was stuck based on its logging messages because a previous execution had not completed (for example):

```
[2019-04-05T20:34:52,500][DEBUG][o.e.x.m.MonitoringService] [node-1] monitoring execution is skipped until previous execution terminated
```

While trying to determine why it might be stuck, we checked the tasks API and noticed that ML's job flush seemed to be stuck:

```
GET /_cat/tasks
cluster:admin/xpack/ml/job/flush    OrGEMv1DSFO70fMjkBXBTA:876532   -                               transport  1551096703043 12:11:43 8.2d        10.11.128.65  instance-0000000046
cluster:admin/xpack/ml/job/flush[n] OrGEMv1DSFO70fMjkBXBTA:876533   OrGEMv1DSFO70fMjkBXBTA:876532   direct     1551096703043 12:11:43 8.2d        10.11.128.65  instance-0000000046
```

At the time, we concluded that the ML job stats call made by ES was stuck and therefore the entire monitoring service was stuck (and being skipped, waiting for the ML call to return).

**Comment by pickypg** [comment]
I think we can close this one out for two reasons, we have since debugged another task issue that was present at the same time as the ML job flush was stuck (example):

```
cluster:admin/xpack/monitoring/bulk Bmfh7f6uS86r9LFwVU-Law:317      -                               transport 1551943836542 07:30:36 28.4d  172.27.99.31   instance-0000000047
```

I diagnosed this in #47, and fixed it in a corresponding ES PR (linked from there).

The more certain part about closing this out is because there were no examples of `cluster:monitor/xpack/ml/job/stats/get` in the tasks API output, which is the indicator for the ML job stats call that monitoring performs.
