### ISSUE TITLE
Phase I: CCR Monitoring

### ISSUE THREAD

**Issue by ycombinator** [elastic/stack-monitoring#8]
This issue tracks the initial phase of https://github.com/elastic/stack-monitoring/issues/4. This phase is deliberately quite simple, and targets the 6.5.0 release along side the beta release of the CCR feature in Elasticsearch.

For this phase we will add two charts to the Index view in the Monitoring UI (concrete URL: http://localhost:5601/app/monitoring#/elasticsearch/indices/testindex):

* A timeseries chart showing two series: number of operations on leader index and number of operations on follower index. The goal of this chart is to let users see how far the follower index is behind the leader index, over time.

* A timeseries chart showing errors over time. There are a few error/failure metrics to choose from so we need to figure out which one(s) we look at concretely. The goal of this chart is to let users know if there are problems creeping up over time, ideally split by types of issues (but we need to see what's available/cardinality/etc.).

Note that while this issue talks about the UI, there is also work needed in the backend to collect the relevant CCR metrics and index them into `.monitoring-*` indices.

Also note that we will build upon this UI in the next iteration, targeting 6.6.0. This issue is, again, just for the first phase.

**Comment by chrisronline** [comment]
This sounds good @ycombinator. I think we should focus on delivering something simple and familiar with our existing monitoring UI and we can easily build upon this in 6.6 once the feature is out of beta. We're on a time crunch as it is with APM for 6.5 so I'd consider anything we can get for 6.5 would be better nothing and what @ycombinator listed here is feasible for 6.5.

**Comment by ruflin** [comment]
We met with the Elasticsearch team to discuss the first implementation. We agreed on the following below:

<img width="938" alt="screen shot 2018-09-11 at 07 35 36" src="https://user-images.githubusercontent.com/244900/45360512-668be980-b595-11e8-92ad-fb7039391085.png">

Details on how all the values are calculated were discussed.

**Comment by bleskes** [comment]
Here is the complete pages with the explanations:

# Required

![image](https://user-images.githubusercontent.com/1006375/45492894-c0dfa280-b76d-11e8-87ac-49b4a6200ad3.png)

![image](https://user-images.githubusercontent.com/1006375/45492748-65151980-b76d-11e8-997f-86a9de624ecc.png)

@chrisronline note that we changed the header of `Sync lag (time)` to `Last fetch time` since we last discussed it.

# Nice to have

![image](https://user-images.githubusercontent.com/1006375/45492946-dd7bda80-b76d-11e8-8c6c-462b5d4349ba.png)

**Comment by chrisronline** [comment]
PR for this work: https://github.com/elastic/kibana/pull/23013

It's still a WIP but the the required UI elements are nearly ready for review

**Comment by yaronp68** [comment]
@ruflin @chrisronline 
Giving the user a table of followers, provides visibility but in order to provide monitoring experience, the user needs to have context around the numbers provided.
- the user needs to have a quick way to know which indices needs to be looked at - filter / sort by having errors and filter/sort by operations lag between leader and follower (calculated )
- The user might like to have a summary row about the table with the numbers of indices that are not ok
- using sparklines in each row for fetched operations vs sparkline of indexed operations in the last 30 minutes or so (depending on the time filter), gives the trend and a perspective

**Comment by bleskes** [comment]
@yaronp68 great suggestions but I would really love to have the above screens first before adding any more features. If EUI makes it easy to sort by a columns, I'm fine with having it.

**Comment by chrisronline** [comment]
@yaronp68 Love the ideas!

> the user needs to have a quick way to know which indices needs to be looked at - filter / sort by having errors and filter/sort by operations lag between leader and follower (calculated )

Definitely - we'll default sort by errors so they bubble to the top but allow the user to sort on any of the columns

> The user might like to have a summary row about the table with the numbers of indices that are not ok

Yup. I added a section at the top indicating this "high level" status

> using sparklines in each row for fetched operations vs sparkline of indexed operations in the last 30 minutes or so (depending on the time filter), gives the trend and a perspective

I'd say let's do this in the next phase as we already have two graphs that give some insight into how the follower is performing on the shard level

Here are some screenshots of what we have right now:

<img width="1387" alt="screen shot 2018-09-17 at 9 22 11 am" src="https://user-images.githubusercontent.com/56682/45625911-0517bf00-ba5c-11e8-83bc-fc01352b2f23.png">
<img width="1388" alt="screen shot 2018-09-17 at 9 22 16 am" src="https://user-images.githubusercontent.com/56682/45625912-0517bf00-ba5c-11e8-9441-015b8722b525.png">
<img width="1381" alt="screen shot 2018-09-17 at 9 28 13 am" src="https://user-images.githubusercontent.com/56682/45625914-0517bf00-ba5c-11e8-9461-4c3d137e2057.png">

(Note: I know the graphs aren't showing anything - actively debugging that now)

**Comment by bleskes** [comment]
@chrisronline Awesome turn around. Let me know when you feel that the PR is ready for review.

> Yup. I added a section at the top indicating this "high level" status

I'm a bit worried on this one - errors are not the only indication of trouble - lag is one too, both in time and in terms of ops. Without taking those into account I feel it's misleading to say "Looking good!". I purposely wanted to avoid having a discussion about what the right defaults should be, which is why we didn't include them in the original mock ups.

**Comment by chrisronline** [comment]
@bleskes 
> I'm a bit worried on this one - errors are not the only indication of trouble - lag is one too, both in time and in terms of ops. Without taking those into account I feel it's misleading to say "Looking good!". I purposely wanted to avoid having a discussion about what the right defaults should be, which is why we didn't include them in the original mock ups.

That's a very valid point. I think and hope we can get to a point where we can attempt to summarize all the data we know into a single "things are good" or "things are not good" but it's not clear right now what entirely constitutes either. Honestly, it might be something the user would need to configure at the end of the day because lag time can vary based on network/hardware constraints, etc.

For now, I'm going to remove it and we can revisit post 6.5

**Comment by yaronp68** [comment]
> @chrisronline Awesome turn around. Let me know when you feel that the PR is ready for review.
> 
> > Yup. I added a section at the top indicating this "high level" status
> 
> I'm a bit worried on this one - errors are not the only indication of trouble - lag is one too, both in time and in terms of ops. Without taking those into account I feel it's misleading to say "Looking good!". I purposely wanted to avoid having a discussion about what the right defaults should be, which is why we didn't include them in the original mock ups.

@bleskes, 2 suggestions for calculating the status (can be added post 6.5):
- If the now - last success fetch > 5 * interval between fetches - we can assume things are not good. 
- If the  lag between leader and follower is growing for the last 10 reads, we can say it is lagging behind
It will always be arbitrary thresholds until we apply ML based thresholds
